### ISSUE TITLE
Inggrit : Individual Project

### ISSUE THREAD

**Issue by inggritenovaleta** [HackYourFutureBelgium/class-13-14#41]
- [x] [repo](https://github.com/inggritenovaleta/inggritenovaleta.github.io.git)
- [x] a great README file
- [x] [live demo](https://inggritenovaleta.github.io/)
- [x] [many small, well-named commits](https://github.com/inggritenovaleta/inggritenovaleta.github.io/commits)

**Comment by iLienstAr** [comment]
👍 Take your time, @inggritenovaleta

**Comment by colevandersWands** [comment]
Well done @inggritenovaleta!  Your HTML and README both have nice tidy code, and the live home page looks nice.  

One thing you can improve for next time is to have more helpful names in your commits.  Instead of "Update index.html" you can write in more detail what you changed with that commit. for example: "created CSS class to style images"

There's plenty of time to practice this in the next 3 weeks.  🚀

**Comment by IrinaSing** [comment]
Wow, that's a beautiful page! Something to inspire :-)
